services:
  - type: web
    name: go-mvp
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: go-mvp-db
          property: connectionString

databases:
  - name: go-mvp-db
    plan: free
